[package]
name = "bosync-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "bosync"
path = "src/main.rs"

[dependencies]
bosync-git = { path = "../bosync-git" }
bosync-cf = { path = "../bosync-cf" }
bosync-core = { path = "../bosync-core" }
bosync-sync = { path = "../bosync-sync" }
anyhow.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap.workspace = true
ctrlc.workspace = true
notify.workspace = true
